"""Refactor user roles to RBAC and implement full repair workflow models

Revision ID: 48cd321ed8a3
Revises: 
Create Date: 2026-03-03 14:06:04.323733

- Remove UserRole enum
- Introduce Role table with many-to-many UserRole association
- Add Client and Manufacturer entities
- Add Device entity with indexed searchable fields
- Add TechnicalDocument and SparePart tables
- Add Intervention table with status enum and signature support
- Add InterventionAttachment table (photo / technical doc)
- Add EmailLog table for manufacturer, client, and company emails
- Configure proper relationships and cascade rules
- Prepare schema for intervention history via Device → Intervention relationship
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48cd321ed8a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('support_phone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index('ix_equipment_brand', 'equipment', ['brand'], unique=False)
    op.create_index('ix_equipment_client_id', 'equipment', ['client_id'], unique=False)
    op.create_index('ix_equipment_manufacturer_id', 'equipment', ['manufacturer_id'], unique=False)
    op.create_index('ix_equipment_model', 'equipment', ['model'], unique=False)
    op.create_index('ix_equipment_serial_number', 'equipment', ['serial_number'], unique=False)
    op.create_index('ix_equipment_type', 'equipment', ['type'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('intervention',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'NOT_REPAIRED', name='intervention_status_enum'), server_default='IN_PROGRESS', nullable=False),
    sa.Column('diagnostic', sa.Text(), nullable=True),
    sa.Column('actions_taken', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('signature_image_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_equipment_id'), 'intervention', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_intervention_technician_id'), 'intervention', ['technician_id'], unique=False)
    op.create_table('spare_part',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('reference_code', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spare_part_equipment_id'), 'spare_part', ['equipment_id'], unique=False)
    op.create_table('technical_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Enum('PDF', 'VIDEO', 'IMAGE', name='document_type_enum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_document_equipment_id'), 'technical_document', ['equipment_id'], unique=False)
    op.create_table('email_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intervention_id', sa.UUID(), nullable=False),
    sa.Column('recipient_type', sa.Enum('MANUFACTURER', 'CLIENT', 'COMPANY', name='recipient_type_enum'), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_log_intervention_id'), 'email_log', ['intervention_id'], unique=False)
    op.create_table('intervention_attachment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intervention_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('attachment_type', sa.Enum('PHOTO', 'TECH_DOC', name='attachment_type_enum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_attachment_intervention_id'), 'intervention_attachment', ['intervention_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intervention_attachment_intervention_id'), table_name='intervention_attachment')
    op.drop_table('intervention_attachment')
    op.drop_index(op.f('ix_email_log_intervention_id'), table_name='email_log')
    op.drop_table('email_log')
    op.drop_index(op.f('ix_technical_document_equipment_id'), table_name='technical_document')
    op.drop_table('technical_document')
    op.drop_index(op.f('ix_spare_part_equipment_id'), table_name='spare_part')
    op.drop_table('spare_part')
    op.drop_index(op.f('ix_intervention_technician_id'), table_name='intervention')
    op.drop_index(op.f('ix_intervention_equipment_id'), table_name='intervention')
    op.drop_table('intervention')
    op.drop_table('user_role')
    op.drop_index('ix_equipment_type', table_name='equipment')
    op.drop_index('ix_equipment_serial_number', table_name='equipment')
    op.drop_index('ix_equipment_model', table_name='equipment')
    op.drop_index('ix_equipment_manufacturer_id', table_name='equipment')
    op.drop_index('ix_equipment_client_id', table_name='equipment')
    op.drop_index('ix_equipment_brand', table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('users')
    op.drop_table('role')
    op.drop_table('manufacturer')
    op.drop_table('client')
    # ### end Alembic commands ###
