"""prevent lazy loading on user-interventions

Revision ID: 4cb5e85a2ef3
Revises: ad8bb993e722
Create Date: 2026-03-04 22:18:25.341342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb5e85a2ef3'
down_revision: Union[str, Sequence[str], None] = 'ad8bb993e722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
