"""prevent lazy loading

Revision ID: 5d6aee8bf0ad
Revises: 4cb5e85a2ef3
Create Date: 2026-03-04 22:22:07.285301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6aee8bf0ad'
down_revision: Union[str, Sequence[str], None] = '4cb5e85a2ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
