"""add image fields

Revision ID: b3bd58b345d0
Revises: 48cd321ed8a3
Create Date: 2026-03-04 14:42:41.973730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3bd58b345d0'
down_revision: Union[str, Sequence[str], None] = '48cd321ed8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('spare_part', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.drop_column('spare_part', 'image')
    op.drop_column('equipment', 'image')
    # ### end Alembic commands ###
